bindkey -v
zstyle ':completion:*' menu select
bindkey -M viins "^[[1;5C" forward-word
bindkey -M viins "^[[1;5D" backward-word
bindkey -M viins '^ ' autosuggest-accept

# spaceship theme
ZSH_THEME="spaceship"

# tmux
function ts() {
  tmux new-session -d -s $1
  tmux switch-client -t $1
}
function tmux-sessionizer() {
  bash -c "~/.local/bin/tmux-sessionizer"
}
zle -N tmux-sessionizer
bindkey -M viins '^F' tmux-sessionizer

function dir() {
  mkdir $1 && cd $1
}

function pr() {
  if [ $1 = "ls" ]; then
    gh pr list
  else
    gh pr checkout $1
  fi
}

function vimcfg() {
  cd ~/.config/datsnvim
  ts vim
}

function vault() {
  cd ~/.config/datsvault
  ts vault
}

export WAKATIME_HOME="$HOME/.config"
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git --color=always"
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
