[general]
import = ["/home/dtsf/.config/alacritty/colors.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "X", mods = "Control | Shift", action = "ToggleViMode" },
]

[terminal.shell]
args = ["-l", "-c", "zellij attach dtsf -c"]
program = "fish"

[window]
opacity = 0.8

[window.padding]
x = 25
y = 25
