#!/bin/sh

variant=$1

if [ -z "$WAYLAND_DISPLAY" ]; then
  if [ "$variant" = "intl" ]; then
    setxkbmap -layout us -variant intl

    notify-send -t 2000 "Keyboard layout" "Switched to international"
  else
    setxkbmap -layout us

    notify-send -t 2000 "Keyboard layout" "Switched to default"
  fi
else
  if [ "$SWAY_SOCKET" ]; then
    if [ "$variant" = "intl" ]; then
      swaymsg input type:keyboard xkb_variant intl

      notify-send -t 2000 "Keyboard layout" "Switched to international"
    else
      swaymsg input type:keyboard xkb_variant '""'

      notify-send -t 2000 "Keyboard layout" "Switched to default"
    fi
  else
    if [ "$variant" = "intl" ]; then
      hyprctl keyword input:kb_variant intl

      notify-send -t 2000 "Keyboard layout" "Switched to international"
    else
      hyprctl reload

      notify-send -t 2000 "Keyboard layout" "Switched to default"
    fi
  fi
fi
