#!/bin/sh

if [ $# -eq 0 ]; then
  echo "no arguments provided"
  exit 1
fi

if [ -d "$1" ]; then
  if [ "${1: -1}" = "/" ]; then
    dir=${1::-1}
  else
    dir=$1
  fi
fi

echo "enter password for zip file"
read -s password

if [ -z "$password" ]; then
  if [ -d "$dir" ]; then
    zip -r $dir.zip $dir
  else
    zip $1.zip $1
  fi
else
  if [ -d "$dir" ]; then
    zip -r -P $password $dir.zip $dir
  else
    zip -P $password $1.zip $1
  fi
fi
