# set colorscheme gruvbox
set -g fish_color_normal "#b8bb26"
set -g fish_color_command "#ebdbb2"
set -g fish_color_quote "#ebdbb2"
set -g fish_color_redirection "#ebdbb2"
set -g fish_color_end "#ebdbb2"
set -g fish_color_error "#fb4934"
set -g fish_color_escape "#fb4934"
set -g fish_color_cwd "#83a598"
set -g fish_color_cwd_root "#fb4934"
set -g fish_color_match "#fb4934"
set -g fish_color_selection "#282828"
set -g fish_color_search_match "#83a598"
set -g fish_color_operator "#83a598"
set -g fish_color_param "#83a598"
set -g fish_color_comment "#928374"
set -g fish_color_history_current "#ebdbb2"
set -g fish_color_host "#83a598"
set -g fish_color_autosuggestion "#83a598"
set -g fish_color_valid_path "#b8bb26"
set -g fish_color_user "#83a598"

# completion pager colors
set -g fish_pager_color_progress "#b8bb26"
set -g fish_pager_color_prefix "#b8bb26"
set -g fish_pager_color_description "#b8bb26"
set -g fish_pager_color_completion "#b8bb26"

# hydro prompt settings with gruvbox dark 
set -g hydro_color_prompt "#ebdbb2"
set -g hydro_color_pwd "#83a598"
set -g hydro_color_git "#83a598"
set -g hydro_color_error "#fb4934"
set -g hydro_color_duration "#b8bb26"
