# set colorscheme gruvbox
set -g fish_color_normal "#fabd2f"
set -g fish_color_command "#fe8019"
set -g fish_color_quote "#fabd2f"
set -g fish_color_redirection "#d3869b"
set -g fish_color_end "#d3869b"
set -g fish_color_error "#fb4934"
set -g fish_color_escape "#fb4934"
set -g fish_color_cwd "#fabd2f"
set -g fish_color_cwd_root "#fb4934"
set -g fish_color_match "#fb4934"
set -g fish_color_selection "#1d2021"
set -g fish_color_search_match "#d3869b"
set -g fish_color_operator "#b8bb26"
set -g fish_color_param "#ebdbb2"
set -g fish_color_comment "#928374"
set -g fish_color_history_current "#fabd2f"
set -g fish_color_host "#fabd2f"
set -g fish_color_autosuggestion "#ebdbb2"
set -g fish_color_valid_path "#83a598"
set -g fish_color_user "#fe8019"

# completion pager colors
set -g fish_pager_color_progress "#fabd2f"
set -g fish_pager_color_prefix "#fabd2f"
set -g fish_pager_color_description "#fabd2f"
set -g fish_pager_color_completion "#fabd2f"

# hydro prompt settings with gruvbox dark 
set -g hydro_color_prompt "#fe8019"
set -g hydro_color_pwd "#8ec07c"
set -g hydro_color_git "#8ec07c"
set -g hydro_color_error "#fb4934"
set -g hydro_color_duration "#8ec07c"
