# set colorscheme oxocarbon
set -g fish_color_normal "#33b1ff"
set -g fish_color_command "#42be65"
set -g fish_color_quote "#33b1ff"
set -g fish_color_redirection "#3ddbd9"
set -g fish_color_end "#3ddbd9"
set -g fish_color_error "#ee5396"
set -g fish_color_escape "#ee5396"
set -g fish_color_cwd "#33b1ff"
set -g fish_color_cwd_root "#ee5396"
set -g fish_color_match "#ee5396"
set -g fish_color_selection "#1d2021"
set -g fish_color_search_match "#3ddbd9"
set -g fish_color_operator "#82cfff"
set -g fish_color_param "#82cfff"
set -g fish_color_comment "#90A4AE"
set -g fish_color_history_current "#33b1ff"
set -g fish_color_host "#33b1ff"
set -g fish_color_autosuggestion "#82cfff"
set -g fish_color_valid_path "#82cfff"
set -g fish_color_user "#42be65"

# completion pager colors
set -g fish_pager_color_progress "#33b1ff"
set -g fish_pager_color_prefix "#33b1ff"
set -g fish_pager_color_description "#33b1ff"
set -g fish_pager_color_completion "#33b1ff"

# hydro prompt settings with gruvbox dark 
set -g hydro_color_prompt "#42be65"
set -g hydro_color_pwd "#be95ff"
set -g hydro_color_git "#be95ff"
set -g hydro_color_error "#ee5396"
set -g hydro_color_duration "#be95ff"
