# general
set -g fish_color_normal "#78dce8"
set -g fish_color_command "#66cccc"
set -g fish_color_quote "#78dce8"
set -g fish_color_redirection "#a9dc76"
set -g fish_color_end "#a9dc76"
set -g fish_color_error "#ff6188"
set -g fish_color_escape "#ff6188"
set -g fish_color_cwd "#78dce8"
set -g fish_color_cwd_root "#ff6188"
set -g fish_color_match "#ff6188"
set -g fish_color_selection "#1e1e1e"
set -g fish_color_search_match "#a9dc76"
set -g fish_color_operator "#66cccc"
set -g fish_color_param "#f8f8f2"
set -g fish_color_comment "#9e9e9e"
set -g fish_color_history_current "#78dce8"
set -g fish_color_host "#78dce8"
set -g fish_color_autosuggestion "#f8f8f2"
set -g fish_color_valid_path "#ffd866"
set -g fish_color_user "#ab9df2"

# completion pager
set -g fish_pager_color_progress "#78dce8"
set -g fish_pager_color_prefix "#78dce8"
set -g fish_pager_color_description "#78dce8"
set -g fish_pager_color_completion "#78dce8"

# hydro prompt
set -g hydro_color_prompt "#78dce8"
set -g hydro_color_pwd "#ab9df2"
set -g hydro_color_git "#ab9df2"
set -g hydro_color_error "#ff6188"
set -g hydro_color_duration "#ab9df2"
