# set tokyonight colorscheme
set -g fish_color_normal "#a9b1d6"
set -g fish_color_command "#a9b1d6"
set -g fish_color_quote "#a9b1d6"
set -g fish_color_redirection "#a9b1d6"
set -g fish_color_end "#a9b1d6"
set -g fish_color_error "#ff6c6b"
set -g fish_color_escape "#ff6c6b"
set -g fish_color_cwd "#7aa2f7"
set -g fish_color_cwd_root "#ff6c6b"
set -g fish_color_match "#ff6c6b"
set -g fish_color_selection "#1f2335"
set -g fish_color_search_match "#7aa2f7"
set -g fish_color_operator "#7aa2f7"
set -g fish_color_param "#7aa2f7"
set -g fish_color_comment "#5c6370"
set -g fish_color_history_current "#a9b1d6"
set -g fish_color_host "#7aa2f7"
set -g fish_color_autosuggestion "#7aa2f7"
set -g fish_color_valid_path "#98c379"
set -g fish_color_user "#7aa2f7"

# completion pager colors
set -g fish_pager_color_completion "#a9b1d6"
set -g fish_pager_color_description "#a9b1d6"
set -g fish_pager_color_prefix "#a9b1d6"
set -g fish_pager_color_progress "#a9b1d6"

# set hydro prompt settings with tokyonight
set -g hydro_color_prompt "#a9b1d6"
set -g hydro_color_pwd "#7aa2f7"
set -g hydro_color_git "#7aa2f7"
set -g hydro_color_error "#ff6c6b"
set -g hydro_color_duration "#98c379"
