#!/bin/sh

source ~/.env

#Autostart
killall sxhkd; sxhkd &
killall dunst; dunst &
# feh --bg-fill $WALLPAPER &
killall xwinwrap; live_wall $WALLPAPER &
killall polybar; $HOME/.config/polybar/launch.sh &

#variable
alias bc='bspc config'
alias br='bspc rule'
c="#151515"

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

#Others
bc border_width 0
bc normal_border_color "$c"
bc focused_border_color "$c"
bc active_border_color "$c"
bc window_gap 8
bc split_ratio 0.45
bc borderless_monocle true
bc gapless_monocle false
