#!/bin/sh

# autostart
killall sxhkd; sxhkd &
killall dunst; dunst &
killall picom; picom -f &
set_wallpaper $HOME/pics/walls/03.jpeg &

if [ -e "$STATUS_FILE" ] && [ "$(cat "$STATUS_FILE")" = "1" ]; then
  killall polybar;
else
  killall polybar; $HOME/.config/polybar/launch.sh &
fi

# variables
alias bc='bspc config'
alias br='bspc rule'

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# others
bc border_width 0
bc window_gap 8
bc split_ratio 0.45
bc borderless_monocle true
bc gapless_monocle false

# rules
br -a Steam desktop='^1'
br -a mpv desktop='^1' follow=on
br -a 'Google-chrome' desktop='^1' follow=on
br -a Chromium desktop='^1' follow=on
br -a discord desktop='^5'
br -a zathura desktop='^6' follow=on
br -a VirtualBox desktop='^9'
br -a qbittorrent desktop='^9'
br -a 'Spotify' desktop='^8'
