[general]
framerate = 60
bars = 96
autosens = 1

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100

[smoothing]
noise_reduction = 40
